version: "3"

services:
  app:
    build: ./docker
    volumes: 
      - ./:/usr/src/TestMVC
    entrypoint:
      - php
      - -S
      - 0.0.0.0:8002
      - -t
      - /usr/src/TestMVC
      - -dxdebug.remote_enable=1
      - -dxdebug.remote_host=172.18.0.1
    ports:
      - 8002:8002
